// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThanhToanTienNuoc.Data;

#nullable disable

namespace ThanhToanTienNuoc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250810135519_ReplaceKhachHangWithNguoiDung")]
    partial class ReplaceKhachHangWithNguoiDung
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThanhToanNuocSach.Models.ChiSoNuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("ChiSoCu")
                        .HasColumnType("real");

                    b.Property<float>("ChiSoMoi")
                        .HasColumnType("real");

                    b.Property<bool>("DaThanhToan")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhachHangId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quy")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ThongBaoZalo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.ToTable("ChiSoNuoc");
                });

            modelBuilder.Entity("ThanhToanTienNuoc.Models.AdminAccount", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AdminID");

                    b.ToTable("AdminAccounts");
                });

            modelBuilder.Entity("ThanhToanTienNuoc.Models.DiaChi", b =>
                {
                    b.Property<int>("DiaChiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiaChiId"));

                    b.Property<string>("TenThon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenXom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiaChiId");

                    b.ToTable("DiaChi");
                });

            modelBuilder.Entity("ThanhToanTienNuoc.Models.NguoiDungs", b =>
                {
                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DiaChiId")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("DiaChiId");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("ThanhToanNuocSach.Models.ChiSoNuoc", b =>
                {
                    b.HasOne("ThanhToanTienNuoc.Models.NguoiDungs", "NguoiDungs")
                        .WithMany("ChiSoNuocs")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("ThanhToanTienNuoc.Models.NguoiDungs", b =>
                {
                    b.HasOne("ThanhToanTienNuoc.Models.DiaChi", "DiaChi")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("DiaChiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaChi");
                });

            modelBuilder.Entity("ThanhToanTienNuoc.Models.DiaChi", b =>
                {
                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("ThanhToanTienNuoc.Models.NguoiDungs", b =>
                {
                    b.Navigation("ChiSoNuocs");
                });
#pragma warning restore 612, 618
        }
    }
}
